# Generated by Django 5.2.1 on 2025-12-06 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_user_managers"),
    ]

    operations = [
        migrations.AddField(
            model_name="sellerprofile",
            name="store_is_open",
            field=models.BooleanField(default=True, help_text="Mağaza satışa açık mı?"),
        ),
        migrations.AddField(
            model_name="user",
            name="block",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="user",
            name="phone",
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name="user",
            name="room_number",
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
