# Generated by Django 5.2.8 on 2025-11-25 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellersubscription',
            name='payment_session_id',
            field=models.CharField(blank=True, help_text='Payment provider session ID', max_length=255),
        ),
        migrations.AlterField(
            model_name='sellersubscription',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
