# Generated by Django 5.2.1 on 2025-12-06 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="delivery_address",
            field=models.TextField(blank=True, help_text="Oda numarası, blok bilgisi"),
        ),
        migrations.AddField(
            model_name="order",
            name="delivery_phone",
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name="order",
            name="delivery_type",
            field=models.CharField(
                choices=[
                    ("customer_pickup", "Müşteri Alacak"),
                    ("seller_delivery", "Satıcı Getirecek"),
                ],
                default="customer_pickup",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="payment_method",
            field=models.CharField(
                choices=[("cash_on_delivery", "Teslim Anında Ödeme")],
                default="cash_on_delivery",
                max_length=50,
            ),
        ),
    ]
